<?php

return array (
  'optdesc' => 'Sie können diese Pakete für eine Instagram-Verlosung mit über 2500 Kommentaren verwenden.',
  'Destek' => 'Technischer Support',
  'Destekalt' => 'Sie können mit Live-Support jederzeit zu unserem technischen Team sprechen.',
  'Memnuniyet' => '100% Kundenzufriedenheit',
  'Memnuniyetalt' => 'Wenn Sie nicht wie unser Dienst tun gekauft Sie Ihr Geld bedingungslos zurückerstattet wird.',
  'yorumnekadar' => 'Wie viele Kommentare enthält dein Instagram-Beitrag?',
  'cekilisfiyat' => 'Preisliste',
  'onekyan' => 'Weniger als',
  'sonekyan' => 'Kommentare',
  '2mfazlayorum' => 'Hast du über 2.000.000 Kommentare zu deinem Instagram-Beitrag?',
  'bizeyaz' => 'Erfahren Preis',
  'dahauygun' => '',
  'sadece' => 'Nur',
  'satinal' => 'Kauf es',
  'nesunuyor' => 'Was können wir tun?',
  'araclar' => 'CekilisGram Werkzeuge',
  'bilgi1' => 'Sie können mit der gleichen Post unbegrenzt zieht machen.',
  'bilgi2' => 'Sie können bestimmen, wie viele Gewinner sein wird.',
  'bilgi3' => 'Sie können Ersatz Gewinner bestimmen.',
  'bilgi4' => 'Sie können mit mehr als einem Instagram Post ziehen.',
  'bilgi5' => 'Tag-Filterung',
  'bilgi6' => 'Wortfilterung',
  'bilgi7' => 'Sie können die Anhänger überprüfen',
  'sayfa' => 'Pakete',
  'list2' => '3 Wiederholungen für den gleichen post',
  'list3' => 'Post Kombinieren',
  'list4' => 'Follower-Steuerung',
  'list5' => 'Wortfilterung',
  'list6' => 'Bestimmen Sie, wie viele Etiketten verlost werden sollen',
  'list7' => 'Keine Zeitbegrenzung',
  'list11' => 'Verlosung von 2500 Kommentar',
  'list12' => 'Verlosung von 5000 Kommentar',
  'list13' => 'Verlosung von 20000 Kommentar',
  'list14' => 'Verlosung von 50000 Kommentar',
  'list15' => 'Verlosung von 150000 Kommentar',
  'list16' => 'Verlosung von 500000 Kommentar',
  'list17' => 'Verlosung von 2000000 Kommentar',
  '1p' => '(Für 1 Beitrag)',
  '3p' => '(Für 3 Beitrag)',
  '5p' => '(Für 5 Beitrag)',
);
