<?php

return array (
  'panel' => 'Panel',
  'destek' => 'Unterstützung',
  'ayarlar' => 'die Einstellungen',
  'cikisyap' => 'Ausloggen',
  'kontrolpaneli' => 'Steuerplatine',
  'merhaba' => 'Hallo',
  'hosgeldin' => 'Willkommen in Cekilisgram',
  'yardim' => 'Können wir dir helfen?',
  'yardim2' => 'Bitte senden Sie eine Supportanfrage.',
  'sta1' => 'Personen mochten ihre letzte Verlosung',
  'sta2' => 'Personen haben die letzte Verlosung kommentiert.',
  'paketiniz' => 'Dein Paket',
  'kadar' => 'Bis zu',
  'kadar2' => 'Kommentare',
  'kaldi' => 'Verlosung übrig',
  'son' => 'Letzte Verlosung(en)',
  'cekilis2' => 'Bitte schreibe die <span style="color:#3a00ff ">Instagram-URL-Adresse</span> um die Verlosung zu organisieren.',
  'adres' => 'URL',
  'ad' => 'Lotteriename',
  'asil' => 'Wie viele Leute werden gewinnen?',
  'takipciyok' => 'Überprüfen Sie nicht die Follower',
  'yedek' => 'Reservesieger',
  'icerdigi' => 'Welche Wörter?',
  'etiket' => 'Wie viele Tags?',
  'baslat' => 'Starten Sie die Verlosung',
  'konu' => 'Gegenstand',
  'aciliyet' => 'Dringlichkeit',
  'acil' => 'Dringend',
  'acildegil' => 'Nicht dringlich',
  'cokacil' => 'Sehr dringend',
  'talindi' => 'ihre Anfrage wurde empfangen',
);
