<?php

return array (
  'optdesc' => 'The easiest way to do Instagram raffle Are you looking for a raffle tool to realize Instagram raffles? You can make raffle from millions of comments immediately and share the results.',
  'opttitle' => 'Instagram Raffle Site - CekilisGram',
  'Anasayfamenu' => 'Main Page',
  'Özelliklermenu' => 'Specifications',
  'Referanslarımızmenu' => 'References',
  'Girişyapmenu' => 'Login',
  'Blogmenu' => 'Blogs',
  'shop' => 'Mağaza',
  'İletişimmenu' => 'Contact',
  'Çekilişyapmenu' => 'Make a Raffle',
  
  
  
  
  'header1' => 'The easiest way to do  <h1 class="font-weight-bold bg-light  px-2 ml-n2" style="width: fit-content;color:#3a00ff;border-radius: 10px">Instagram raffle</h1>',
  'header2' => 'Are you looking for a raffle tool to realize Instagram raffles? You can make raffle from millions of comments immediately and share the results.',
  'headerbuton' => 'Make a Raffle',
  'kullanım' => 'How to use CekilisGram?',
  'headerlist1' => 'Tried and Reliable!',
  'headerlist2' => 'Useful!',
  'headerlist3' => 'User Friendly!',
  'rakamlarbaslik1' => 'At the summit!',
  'rakamlarbaslik2' => 'Statistics',
  'rakamlarcekilis' => 'Pieces',
  'rakamlarcekilis2' => 'of raffles were made by the cekilisgram.',
  'rakamlarkullanici' => 'People',
  'rakamlarkullanici2' => 'used Cekilisgram for maked a raffle on the Instagram',
  'rakamlaryorum' => 'Comments',
  'rakamlaryorum2' => 'Instagram raffle site where customers Continuous make positive comments',
  'enguvicerik' => 'We use social media as a mass media in last years.<br><br>If someone says social media, what comes to your mind first? Of course, Instagram. Instagram is a social media platform that hosts millions of users. There are millions of users, brands, entertainment services, and boutiques on Instagram. These pages are in constant competition on Instagram.<br><br>In order to get an audience on Instagram, it is necessary to advertise to the target audience. It is possible but an expensive way to do this with Instagram sponsored ads. The easiest and cheapest way to advertise on Instagram is to organize an Instagram raffle. As a result of the Instagram raffle you organize, your number of followers increases and you can sell more products.',
  'enguvbaslik' => 'Most Reliable Website for organizing Instagram Raffle',
  'sorgubaslik1' => 'Instagram Raffle Result Inquiry',
  'sorgubaslik2' => 'Is the code you are inquiring about not working? Be sure to get the correct code from the person who organized the Instagram raffle.',
  'igcbaslik1' => 'What is Instagram Raffle?',
  'igcbaslik2' => 'How to make Instagram Raffle?',
  'igcacik1' => 'In order to increase your followers, your brand awareness, your orders, and sustainability on Instagram, Instagram raffles is one of the most important pr and promotional works. The Instagram raffle is an advertising tool in which profiles such as brands and humor accounts, which are appreciated by people and followed very fondly, initiate the raffle by promising products that will attract their followers. For example; Nowadays, choosing products such as a recently released mobile phone, tablet, computer, and cosmetics will increase participation in the raffle more than expected and encourage other people to participate in the raffle. First reason to make a raffle is to earn followers. With the conditions you run for the campaign, you can reach millions of people in days and gain hundreds of thousands of followers thanks to the elements such as sharing your campaign in the story and tagging your friend. At the same time, make a raffle is the most logical advertising method to gain the target audience.',
  'igcacik2' => 'On our website; You can choose the winner with the filtering you have chosen among millions of comments in seconds, and share it as a url with your followers. While cekilisgram.com gives our new users the right to draw 1 use for the raffle, it is preferred by tens of users with our affordable packages.',
  'referanslarimiz' => 'References',
  'listbaslik1' => 'The world\'s best Instagram raffle site',
  'listbaslik2' => 'Fastest Instagram Raffle Website',
  'list1' => 'If the raffle you organize is less than 1000 comments, you do not need to pay.',
  'list2' => 'Thanks to the advanced management screen, you can make raffle with different rules.',
  'list3' => 'Your personal information never records by Cekilisgram. A high level of customer safety is provided.',
  'list4' => 'It offers the most aesthetic image among Instagram raffle sites with its extraordinary animations.',
  'list5' => 'You can save your Instagram raffle and share it with your followers.',
  'ozelliklerbaslik' => 'Why should you use Cekilisgram?',
  'ozelb1' => 'Lottery Algorithm',
  'ozel1' => 'The algorithm developed by a professional software team.',
  'ozelb2' => 'Fast Instagram Raffle',
  'ozel2' => 'You can set the raffle time.',
  'ozelb3' => 'The Best Design',
  'ozel3' => 'Interfaces developed by the best designers in the world.',
  'ozelb4' => 'Cheapest Raffle Packs',
  'ozel4' => 'The lowest-paid to Instagram raffle packs on the market.',
  'ozelb5' => 'Fair Lottery Terms',
  'ozel5' => '100% fair draw, thanks to the unique lottery algorithm.',
  'ozelb6' => '24/7 Customer Service',
  'ozel6' => 'Fast customer service with Whatsapp.',
  'alt1' => 'We are ready for the Instagram raffle. Are you ready for a raffle?',
  'alt2' => 'Try Cekilisgram for free.',
  'altb1' => 'Sign-Up',
  'ara' => 'Search',
  'cekilissorgu' => 'Instagram Raffle Result Inquiry',
  
  
  
  
  'fiyatlandirma' => 'Prices',
  'hakkimizda' => 'About Us',
  'kurumsaliletisim' => 'Corporate communications',
  'gizlilikpolitikasi' => 'Privacy Policy',
  'cerezpolitikasi' => 'Cookies',
  'iptalveiade' => 'Return policy',
  'title' => 'Instagram Raffle Site',
  'ara' => 'Search',
  'cekilissorgu' => 'Instagram Raffle Result Inquiry',
  'footer1' => 'All Rights Reserved',
  'footer2' => 'Last Updated: 06.01.2021',
  'footer3' => 'Update history',
);
