<?php

return array (
  'optdesc' => 'You can use these packages for an Instagram raffle with over 2500 comments.',
  'Destek' => 'Technical Support',
  'Destekalt' => 'You can talk to our technical team at any time with live support.',
  'Memnuniyet' => '100% Customer Satisfaction',
  'Memnuniyetalt' => 'If you do not like our service you purchased your money will be refunded unconditionally.',
  'yorumnekadar' => 'How many comments are there on your Instagram post?',
  'cekilisfiyat' => 'Price List',
  'onekyan' => 'Less than',
  'sonekyan' => 'comments',
  '2mfazlayorum' => 'Got over 2,000,000 comments on your Instagram post?',
  'bizeyaz' => 'Get Price',
  'dahauygun' => '',
  'sadece' => 'Only',
  'satinal' => 'Buy It',
  'nesunuyor' => 'What can we do?',
  'araclar' => 'CekilisGram Tools',
  'bilgi1' => 'You can make unlimited draws with the same post.',
  'bilgi2' => 'You can determine how many winners will be.',
  'bilgi3' => 'You can determine substitute winners.',
  'bilgi4' => 'You can draw with more than one Instagram post.',
  'bilgi5' => 'Tag filtering',
  'bilgi6' => 'Word filtering',
  'bilgi7' => 'You can check the followers',
  'sayfa' => 'Packets',
  'list2' => '3 reps for the same post',
  'list3' => 'Post-Combine',
  'list4' => 'Follower Control',
  'list5' => 'Word Filtering',
  'list6' => 'Determine how many labels to raffle',
  'list7' => 'No time limit',
  'list11' => 'Raffle from 2500 comment',
  'list12' => 'Raffle from 5000 comment',
  'list13' => 'Raffle from 20000 comment',
  'list14' => 'Raffle from 50000 comment',
  'list15' => 'Raffle from 150000 comment',
  'list16' => 'Raffle from 500000 comment',
  'list17' => 'Raffle from 2000000 comment',
  '1p' => '(For 1 Post)',
  '3p' => '(For 3 Post)',
  '5p' => '(For 5 Post)',
);
