<?php

return array (
  'panel' => 'Panel',
  'destek' => 'Support',
  'ayarlar' => 'Settings',
  'cikisyap' => 'Sign Out',
  'kontrolpaneli' => 'Control Board',
  'merhaba' => 'Hi',
  'hosgeldin' => 'Welcome to Cekilisgram',
  'yardim' => 'Can we help you?',
  'yardim2' => 'Please submit a support request.',
  'sta1' => 'People liked their last raffle.',
  'sta2' => 'People commented on the last raffle.',
  'paketiniz' => 'Your package',
  'kadar' => 'Up to',
  'kadar2' => 'comments',
  'kaldi' => 'Raffle(s) Left',
  'son' => 'Recent Raffle(s)',
  'cekilis2' => 'Please write the <span style="color:#3a00ff ">Instagram URL address </span> to organize raffle.',
  'adres' => 'Link',
  'ad' => 'Lottery (Raffle) Name',
  'asil' => 'How many people will win?',
  'takipciyok' => 'Do not check followers',
  'yedek' => 'Reserve winner',
  'icerdigi' => 'Which words?',
  'etiket' => 'How many tags?',
  'baslat' => 'Start the Raffle',
  'konu' => 'Subject',
  'aciliyet' => 'Urgency',
  'acildegil' => 'Not urgent',
  'acil' => 'Urgent',
  'cokacil' => 'Very urgent',
  'talindi' => 'Your request has been received',
);
