<?php

return array (
  'optdesc' => 'Instagram çekiliş yapmanın en kolay yolu Instagram çekilişlerinizi gerçekleştirmek için çekiliş aracı mı arıyorsunuz? Milyonlarca yorumdan hemen çekiliş yapabilir ve sonuçları paylaşabilirsiniz.',
  'opttitle' => 'Ücretsiz Instagram Çekiliş Sitesi - CekilisGram',
  'Anasayfamenu' => 'Anasayfa',
  'Özelliklermenu' => 'Özellikler',
  'Referanslarımızmenu' => 'Referanslarımız',
  'Blogmenu' => 'Blog',
  'İletişimmenu' => 'İletişim',
  'Girişyapmenu' => 'Giriş Yap',
  'Çekilişyapmenu' => 'Çekiliş Yap',
  
  
  'header1' => '<h1 class="font-weight-bold bg-light px-2 ml-n2" style="width: fit-content;color:#3a00ff;border-radius: 10px">Instagram çekiliş</h1> yapmanın en kolay yolu',
  'header2' => 'Instagram çekilişlerinizi gerçekleştirmek için çekiliş aracı mı arıyorsunuz? Milyonlarca yorumdan hemen çekiliş yapabilir ve sonuçları paylaşabilirsiniz.',
  'headerbuton' => 'Çekiliş Yap',
  'kullanım' => 'Çekilişgram Nasıl Kullanılır?',
  'headerlist1' => 'Güvenilir!',
  'headerlist2' => 'Kullanışlı!',
  'headerlist3' => 'Kullanıcı Dostu!',
  'rakamlarbaslik1' => 'Zirvede tek!',
  'rakamlarbaslik2' => 'İstatistikler',
  'rakamlarcekilis' => 'Çekiliş',
  'rakamlarcekilis2' => 'Cekilisgram Tarafından Gerçekleştirildi.',
  'rakamlarkullanici' => 'Kullanıcı',
  'rakamlarkullanici2' => 'Çekilişgram kullanarak Instagram çekilişi yaptı',
  'rakamlaryorum' => 'Yorum',
  'rakamlaryorum2' => 'ile hakkında en çok olumlu yorum yapılan çekiliş sitesi oldu',
  'enguvbaslik' => 'En Güvenilir Instagram Çekiliş Sitesi',
  'enguvicerik' => 'Günümüz teknolojisinde, kitle iletişim aracı olarak en çok sosyal medya kullanıyor.<br><br>Peki, sosyal medya dediğinde ilk olarak aklınıza ne geliyor? Tabii ki Instagram, instagram milyonlarca kullanıcıya ev sahipliği yapan, sosyal medya platformudur. Instagram üzerinde milyonlarca kullanıcı, marka, eğlence hizmeti sağlayan mizah profilleri ve butik gibi hesaplar, bu sosyal medya platformu üzerinde rekabet içerisindedir.<br><br>Instagram üzerinde kitle edinmek için hedef kitleye yönelik reklam yapmak gerekir. Instagram sponsorlu reklamlar ile bunu yapmak mümkün ama pahalı bir yoldur. Instagram üzerinde en kolay reklam yapma yolu, aynı kategoriye sahip profiller ile ortaklaşa instagram çekilişi düzenlemektir. Düzenlediğiniz Instagram çekilişleri sonucunda takipçi sayınız artar ve daha çok ürün satışı yaparsınız.',
  'sorgubaslik1' => 'Instagram Çekiliş Sonucu Sorgula',
  'sorgubaslik2' => 'Hatalı, eksik ya da fazla haneli kodları lütfen Instagram Çekiliş yapan sayfa sahibine sorunuz!',
  'igcbaslik1' => 'Instagram Çekilişi Nedir?',
  'igcbaslik2' => 'Instagram Çekilişi Nasıl Yapılır?',
  'igcacik1' => 'Instagram üzerinde takipçi sayınızı, marka bilinirliğini, sipariş sayınızı ve sürdürebilirliğinizi arttırmak için önde gelen pr ve tanıtım çalışmalarının başında instagram çekiliş yapmak gelir. İnstagram çekiliş, markaların ve insanlar tarafından takdir edilen ve çok severek takip edilen mizah profilleri gibi vb profillerin, takipçilerini cezbedecek ürünleri vaat ederek çekilişi başlattığı bir reklam aracıdır. Örneğin ; günümüzde yeni çıkmış bir cep telefonu, tablet, bilgisayar, kozmetik ürünleri gibi ilgi odağının artacağı ürünler seçmek çekilişe katılımı beklenenden fazla bir şekilde arttırır ve başka insanların da çekilişe katılmasını teşfik eder. Çekiliş yapmanın bir diğer püf noktası ise, çekilişe şart koşmaktır. Kampanya\' ya koştuğunuz şartlar ile, yaptığınız kampanyayı story de paylaşmak, arkadaşını etiketlemek gibi unsurlar sayesinde günler içerisinde reklamınız milyonlarca kişiye erişebilir yüz binlerce takipçi kazanabilirsiniz. Aynı zamanda çekiliş yapmak, hedef kitle kazanmak için en mantıklı reklam yöntemidir.',
  'igcacik2' => 'Cekilisgram.com sitemizde sonuçlandırarak saniyeler içerisinde milyonlarca yorum arasından belirlediğiniz filtrelemeler ile kazanan kişiyi seçebilir, takipçilerinize link olarak sunabilirsiniz. cekilisgram.com, yeni kullanıcılarımıza 1 kullanımlık çekiliş hakkı verirken, uygun fiyatlı paketlerimiz ile onlarca kullanıcının tercihi oluyor.',
  'referanslarimiz' => 'Referanslarımız',
  'listbaslik1' => 'Türkiye’nin en büyük instagram çekiliş sitesi',
  'listbaslik2' => 'En Hızlı Instagram Çekilişi',
  'list1' => '1000 Yoruma kadar olan instagram çekilişleri için para ödemeniz gerekmez.',
  'list2' => 'Gelişmiş yönetim ekranı sayesinde farklı kurallarla instagram çekilişi yapabilirsiniz.',
  'list3' => 'Kişisel bilgileriniz kaydedilmez. Üst düzey müşteri güvenliği sağlanır.',
  'list4' => 'Birbirinden güzel animasyonlarla instagram çekiliş siteleri arasında en estetik görüntüyü sunar.',
  'list5' => 'Yaptığınız çekilişi kaydedebilir ve takipçilerinizle paylaşabilirsiniz.',
  'ozelliklerbaslik' => 'Cekilisgram’ı Farklı Kılanlar',
  'ozelb1' => 'Çekiliş Algoritması',
  'ozelb2' => 'Hızlı Instagram Çekilişi',
  'ozelb3' => 'En İyi Tasarım',
  'ozelb4' => 'Uygun Çekiliş Paketleri',
  'ozelb5' => 'Adil Çekiliş Şartları',
  'ozelb6' => '7/24 Müşteri Desteği',
  'ozel1' => 'Profesyonel yazılım ekibi tarafından geliştirilen algoritma.',
  'ozel2' => 'İsteğinize göre ayarlanabilir çekiliş süresi.',
  'ozel3' => 'Ülkenin en iyi tasarımcıları tarafından geliştirilen arayüzler.',
  'ozel4' => 'Piyasadaki en uygun ücretli instagram çekiliş paketleri.',
  'ozel5' => 'Benzersiz çekiliş algoritması sayesinde %100 adil çekiliş.',
  'ozel6' => 'Günün her saati WhatsApp desteği.',
  'alt1' => 'Instagram çekilişi için biz hazırız. Ya siz?',
  'alt2' => 'Takipçilerini daha fazla bekletme. Cekilisgram kalitesini ücretsiz dene.',
  'altb1' => 'Kayıt Ol',
  'ara' => 'Ara',
  'cekilissorgu' => 'Çekiliş Kodu Sorgula',
  
  
  
  'fiyatlandirma' => 'Fiyatlandırma',
  'hakkimizda' => 'Hakkımızda',
  'gizlilikpolitikasi' => 'Gizlilik Politikası',
  'cerezpolitikasi' => 'Çerezler',
  'iptalveiade' => 'İptal ve İade',
  'kurumsaliletisim' => 'Kurumsal İletişim',
  'title' => 'Instagram Çekiliş Sitesi',
  'footer1' => 'CekilisGram Türk Patent Enstitüsünün 2020/163280 dosya numarası ile koruma altına aldığı ticari bir markadır.<br>Sitedeki yazılı ve görsel materyallerin tamamı ya da bir kısmı kaynak gösterilmeden kullanılamaz.',
  'footer2' => 'Son güncelleme 06.01.2021',
  'footer3' => 'Güncelleme Geçmişi',
  'footermenu1' => 'CekilisGram Anasayfa',
  'footermenu2' => 'Instagram Çekiliş Yap',
  'footermenu3' => 'Instagram Çekiliş Fiyatları',
  'footermenu4' => 'Sosyal Medya Blogu',
  'footermenu5' => 'CekilisGram İletişim',
  'footermenu6' => 'CekilisGram Kurumsal Bilgiler',
  'footermenu7' => 'CekilisGram Kurumsal İletişim',
  'footermenu8' => 'CekilisGram Gizlilik Politikası',
  'footermenu9' => 'CekilisGram Çerez Politikası',
  'footermenu10' => 'CekilisGram İptal ve İade Politikası',
  'footermenu11' => 'KVKK',
  'footermenu12' => 'Instagram Çekiliş Aracı',
  'footermenu13' => 'Instagram Çekilişi Nasıl Yapılır?',
  'footermenu14' => 'Çekiliş Kodu Sorgulama Aracı',
  'footermenu15' => 'Instagram Takipçi',
  'footermenu16' => 'Instagram Takipçi Satın Al',
);
