<?php

return array (
  'optdesc' => '2500 yorum üzerindeki instagram çekilişleri için bu paketleri kullanabilirsiniz.',
  'Destek' => 'Destek Garantisi',
  'Destekalt' => 'Takıldığınız bir yer olursa bize ulaşmaktan çekinmeyin.',
  'Memnuniyet' => 'Memnuniyet Garantisi',
  'Memnuniyetalt' => 'Aldığınız hizmeti beğenmezseniz koşulsuz şartsız paranız iade.',
  'yorumnekadar' => 'Gönderinizde ne kadar yorum var?',
  'cekilisfiyat' => 'Instagram Çekiliş Fiyatları',
  'onekyan' => '',
  'sonekyan' => 'Yorumdan az',
  '2mfazlayorum' => '2M+ Yorumunuz mu var?',
  'bizeyaz' => 'Bize Yazın!',
  'dahauygun' => 'Yerine Şimdi Daha Uygun',
  'sadece' => 'SADECE',
  'satinal' => 'Satın Al',
  'nesunuyor' => 'Çekilişgram size neler sunuyor?',
  'araclar' => 'Cekilisgram Araçları',
  'bilgi1' => 'Aynı Gönderi İle Sınırsız Çekiliş Yapma',
  'bilgi2' => 'Kazanan Sayısı Belirleme',
  'bilgi3' => 'Yedek Sayısı Belirleme',
  'bilgi4' => 'Post Birleştirme Özelliği',
  'bilgi5' => 'Etiket Sayısına Göre Filtreleme',
  'bilgi6' => 'Kelime Filtreleme',
  'bilgi7' => '4 Farklı Takip Kontrolü Seçeneği',
  'sayfa' => 'Paketler',
  'list11' => '2500 Yoruma Kadar Olan',
  'list12' => '5000 Yoruma Kadar Olan',
  'list13' => '20000 Yoruma Kadar Olan',
  'list14' => '50000 Yoruma Kadar Olan',
  'list15' => '150000 Yoruma Kadar Olan',
  'list16' => '500000 Yoruma Kadar Olan',
  'list17' => '2000000 Yoruma Kadar Olan',
  'list2' => 'Aynı gönderi için 3 tekrarlama',
  'list3' => 'Post Birleştirme Özelliği',
  'list4' => 'Takip Kontrolü Özelliği',
  'list5' => 'Kelime Filtreleme Özelliği',
  'list6' => 'Etiket Sayısı Belirleme Özelliği',
  'list7' => 'Süre Sınırı Yok',
  '1p' => '1 Gönderi İçin',
  '3p' => '3 Gönderi İçin',
  '5p' => '5 Gönderi İçin',
);
