<?php

return array (
  'panel' => 'Panel',
  'destek' => 'Destek',
  'ayarlar' => 'Ayarlar',
  'cikisyap' => 'Çıkış Yap',
  'kontrolpaneli' => 'Kontrol Paneli',
  'merhaba' => 'Merhaba',
  'hosgeldin' => 'Çekilişgram’a tekrar hoşgeldiniz',
  'yardim' => 'Yardım mı Lazım?',
  'yardim2' => 'Menüden bize destek talebi gönderebilirsin.',
  'sta1' => 'Son çekilişinizi beğenen kişi sayısı.',
  'sta2' => 'Son çekilişinizin yorum sayısı.',
  'paketiniz' => 'Paketiniz',
  'kadar' => '->',
  'kadar2' => 'Yoruma Kadar',
  'kaldi' => 'Çekiliş Hakkınız Kaldı',
  'son' => 'Son Yapılan Çekilişler',
  'cekilis2' => 'Çekiliş yapmak istediğiniz <span style="color:#3a00ff ">Instagram Gönderisinin adresini</span> buraya yapıştırın.',
  'adres' => 'Post Adresi',
  'ad' => 'Çekiliş Adı',
  'asil' => 'Asıl Talihli Sayısı',
  'takipciyok' => 'Takipçi kontrolü yok',
  'yedek' => 'Yedek Talihli',
  'icerdigi' => 'İçerdiği kelimeler',
  'etiket' => 'En az etiket sayısı',
  'baslat' => 'Çekilişi Başlat',
  'konu' => 'Konu',
  'aciliyet' => 'Aciliyet',
  'cokacil' => 'Çok acil',
  'acil' => 'Acil',
  'acildegil' => 'Acil değil',
  'talindi' => 'Talebiniz alındı',
);
