<?php

return array (
  'optdesc' => 'Il modo più semplice per fare lotteria su Instagram Stai cercando uno strumento di lotteria per realizzare lotterie su Instagram? Puoi fare sorteggio da milioni di commenti immediatamente e condividere i risultati.',
  'opttitle' => 'Sito della lotteria Instagram - CekilisGram',
  'Anasayfamenu' => 'Pagina Principale',
  'Özelliklermenu' => 'Specificazioni',
  'Çekilişyapmenu' => 'Fare una Lotteria',
  'Referanslarımızmenu' => 'Riferimenti',
  'Blogmenu' => 'Blog',
  'shop' => 'Mağaza',
  'İletişimmenu' => 'Contatto',
  'Girişyapmenu' => 'Accesso',
  
  
  
  'header1' => 'Il modo più semplice per fare <h1 class="font-weight-bold bg-light  px-2 ml-n2" style="width: fit-content;color:#3a00ff;border-radius: 10px"> lotteria su Instagram</h1>',
  'header2' => 'Stai cercando uno strumento di lotteria per realizzare lotterie su Instagram? Puoi fare sorteggio da milioni di commenti immediatamente e condividere i risultati.',
  'headerbuton' => 'Fare una Lotteria',
  'kullanım' => 'Come si usa CekilisGram?',
  'headerlist1' => 'Provato e Affidabile!',
  'headerlist2' => 'Utile!',
  'headerlist3' => 'Di facile utilizzo!',
  'rakamlarbaslik1' => 'Al vertice!',
  'rakamlarbaslik2' => 'Statistica',
  'rakamlarcekilis' => 'lotterie',
  'rakamlarcekilis2' => 'sono state detenute da Cekilisgram.',
  'rakamlarkullanici' => 'Persone',
  'rakamlarkullanici2' => 'usano una Cekilisgram per organizzare una lotteria su Instagram',
  'rakamlaryorum' => 'Commento',
  'rakamlaryorum2' => 'Sito della lotteria di Instagram in cui i clienti Continui esprimono commenti positivi.',
  'enguvbaslik' => 'Sito Web più affidabile per l\'organizzazione di Instagram Raffle',
  'enguvicerik' => 'Usiamo i social media come mass media negli ultimi anni.<br><br>Se qualcuno dice i social media, cosa ti viene in mente prima? Certo, Instagram. Instagram è una piattaforma di social media che ospita milioni di utenti. Ci sono milioni di utenti, marchi, servizi di intrattenimento e boutique su Instagram. Queste pagine sono in costante competizione su Instagram.<br><br>Per ottenere un pubblico su Instagram, è necessario fare pubblicità al pubblico di destinazione. È possibile, ma un modo costoso per farlo con gli annunci sponsorizzati da Instagram. Il modo più semplice ed economico per fare pubblicità su Instagram è organizzare una lotteria Instagram. Come risultato della lotteria Instagram che organizzi, il tuo numero di follower aumenta e puoi vendere più prodotti.',
  'sorgubaslik1' => 'Risultati della lotteria di Instagram',
  'sorgubaslik2' => 'Il codice non funziona? Assicurati di ottenere il codice corretto dalla persona che ha modificato la lotteria Instagram.',
  'igcbaslik1' => 'Cos\'è Instagram Raffle?',
  'igcbaslik2' => 'Come fare Instagram Raffle?',
  'igcacik1' => 'Al fine di aumentare i tuoi follower, la consapevolezza del tuo marchio, i tuoi ordini e la sostenibilità su Instagram, le lotterie di Instagram sono una delle più importanti opere promozionali e promozionali. La lotteria Instagram è uno strumento pubblicitario in cui profili come marchi e account umoristici, che sono apprezzati dalle persone e seguiti con molto affetto, iniziano la lotteria con prodotti promettenti che attireranno i loro follower. Per esempio; Al giorno d\'oggi, la scelta di prodotti come telefoni cellulari, tablet, computer e cosmetici rilasciati di recente aumenterà la partecipazione alla lotteria più del previsto e incoraggerà altre persone a partecipare alla lotteria. Il primo motivo per fare una lotteria è guadagnare seguaci. Con le condizioni per la campagna, puoi raggiungere milioni di persone in pochi giorni e guadagnare centinaia di migliaia di follower grazie a elementi come condividere la tua campagna nella storia e taggare il tuo amico. Allo stesso tempo, fare una lotteria è il metodo pubblicitario più logico per ottenere il pubblico di destinazione.',
  'igcacik2' => 'Sul nostro sito Web; Puoi scegliere il vincitore con il filtro che hai scelto tra milioni di commenti in pochi secondi e condividerlo come url con i tuoi follower. Mentre cekilisgram.com offre ai nostri nuovi utenti il diritto di disegnare 1 utilizzo per la lotteria, è preferito da decine di utenti con i nostri pacchetti convenienti.',
  'referanslarimiz' => 'Riferimenti',
  'listbaslik1' => 'Il miglior sito di lotteria Instagram al mondo',
  'listbaslik2' => 'Il sito web di lotteria Instagram più veloce',
  'list1' => 'Se la lotteria che organizzi è inferiore a 1000 commenti, non è necessario pagare.',
  'list2' => 'Con la schermata di gestione avanzata, puoi organizzare una Instagram lotteria con regole diverse.',
  'list3' => 'Le tue informazioni personali non vengono mai registrate da Cekilisgram. Viene fornito un elevato livello di sicurezza per il cliente.',
  'list4' => 'Offre l\'immagine più estetica tra i siti di lotteria di Instagram con le sue straordinarie animazioni.',
  'list5' => 'Puoi salvare la tua lotteria Instagram e condividerla con i tuoi follower.',
  'ozelliklerbaslik' => 'Perché dovresti usare Cekilisgram?',
  'ozelb1' => 'Algoritmo della lotteria',
  'ozel1' => 'L\'algoritmo sviluppato da un team di software professionale.',
  'ozelb2' => 'Raffle veloce su Instagram',
  'ozel2' => 'Puoi impostare il tempo della lotteria.',
  'ozelb3' => 'Il miglior design',
  'ozel3' => 'Interfacce sviluppate dai migliori designer del mondo.',
  'ozelb4' => 'Pacchetti lotteria economici',
  'ozel4' => 'I pacchetti di lotterie più economici sul mercato per Instagram.',
  'ozelb5' => 'Lotteria equa',
  'ozel5' => 'La lotteria è equa al 100% grazie al suo algoritmo unico.',
  'ozelb6' => 'Servizio clienti 24/7',
  'ozel6' => 'Servizio clienti veloce con Whatsapp.',
  'alt1' => 'Siamo pronti per la lotteria di Instagram. Sei pronto per una lotteria?',
  'alt2' => 'Prova Cekilisgram gratuitamente.',
  'altb1' => 'Registrati',
  'ara' => 'Ricerca',
  'cekilissorgu' => 'Risultati della lotteria di Instagram',
  
  
  
  
  
  'fiyatlandirma' => 'Prezzi',
  'hakkimizda' => 'Riguardo a noi',
  'kurumsaliletisim' => 'Comunicazioni aziendali',
  'gizlilikpolitikasi' => 'politica sulla riservatezza',
  'cerezpolitikasi' => 'Cookies',
  'iptalveiade' => 'Politica di ritorno',
  'title' => 'Sito della lotteria di Instagram',
  'ara' => 'Ricerca',
  'cekilissorgu' => 'Risultati della lotteria di Instagram',
  'footer1' => 'Tutti i diritti riservati',
  'footer2' => 'Ultimo aggiornamento: 06.01.2021',
  'footer3' => 'Aggiorna la cronologia',
);
