<?php

return array (
  'optdesc' => 'Puoi utilizzare questi pacchetti per una lotteria Instagram con oltre 2500 commenti.',
  'Destek' => 'Support Technique',
  'Destekalt' => 'Vous pouvez parler à notre équipe technique à tout moment avec le soutien direct.',
  'Memnuniyet' => '100% Satisfaction des clients',
  'Memnuniyetalt' => 'Si vous ne le faites pas comme notre service que vous avez acheté votre argent sera remboursé sans condition.',
  'yorumnekadar' => 'Quanti commenti ci sono sul tuo post di Instagram?',
  'cekilisfiyat' => 'Listino Prezzi',
  'onekyan' => 'Moins de commentaires',
  'sonekyan' => '',
  '2mfazlayorum' => 'Vous avez plus de 2.000.000 commentaires sur votre message Instagram?',
  'bizeyaz' => 'Obtenez Prix',
  'dahauygun' => '',
  'sadece' => 'Seulement',
  'satinal' => 'Compralo',
  'nesunuyor' => 'Que pouvons-nous faire?',
  'araclar' => 'CekilisGram Outils',
  'bilgi1' => 'Vous pouvez faire illimitée avec le même tirages poste.',
  'bilgi2' => 'Vous pouvez déterminer le nombre de gagnants seront.',
  'bilgi3' => 'Vous pouvez déterminer les gagnants de substitution.',
  'bilgi4' => "Vous pouvez dessiner avec plus d'un poste Instagram.",
  'bilgi5' => 'Filtrage Tag',
  'bilgi6' => 'Filtrage de mots',
  'bilgi7' => 'Vous pouvez vérifier les abonnés',
  'sayfa' => 'Pacchetti',
  'list2' => '3 ripetizioni per lo stesso post',
  'list3' => 'Post-Combine',
  'list4' => 'Controllo follower',
  'list5' => 'Filtro parole',
  'list6' => 'Determina quante etichette estrarre',
  'list7' => 'Nessun limite di tempo',
  'list11' => 'Lotteria da 2500 commenti',
  'list12' => 'Lotteria da 5000 commenti',
  'list13' => 'Lotteria da 20000 commenti',
  'list14' => 'Lotteria da 50000 commenti',
  'list15' => 'Lotteria da 150000 commenti',
  'list16' => 'Lotteria da 500000 commenti',
  'list17' => 'Lotteria da 2000000 commenti',
  '1p' => '(Per 1 post)',
  '3p' => '(Per 3 post)',
  '5p' => '(Per 5 post)',
);
