<?php

return array (
  'panel' => 'Pannello',
  'destek' => 'Supporto',
  'ayarlar' => 'Impostazioni',
  'cikisyap' => 'Disconnettersi',
  'kontrolpaneli' => 'Pannello di controllo',
  'merhaba' => 'Ciao',
  'hosgeldin' => 'Benvenuti in Cekilisgram',
  'yardim' => 'Possiamo aiutarti?',
  'yardim2' => 'Si prega di inviare una richiesta di supporto.',
  'sta1' => 'Persone è piaciuta la loro ultima lotteria',
  'sta2' => 'Persone hanno commentato l\'ultima lotteria',
  'paketiniz' => 'Pacchetto della lotteria',
  'kadar' => 'Fino a',
  'kadar2' => 'commenti',
  'kaldi' => 'Lotteria rimaste',
  'son' => 'Raffle Recenti',
  'cekilis2' => 'Scrivi l\'indirizzo <span style="color:#3a00ff ">URL di Instagram </span> per organizzare la lotteria.',
  'adres' => 'URL',
  'ad' => 'Nome della lotteria',
  'asil' => 'Quante persone vinceranno?',
  'takipciyok' => 'Non controllare i follower',
  'yedek' => 'Vincente di riserva',
  'icerdigi' => 'Quali parole?',
  'etiket' => 'Quanti tag?',
  'baslat' => 'Inizia la lotteria',
  'konu' => 'Soggetto',
  'aciliyet' => 'Urgenza',
  'acil' => 'Urgente',
  'acildegil' => 'Non urgente',
  'cokacil' => 'Molto urgente',
  'talindi' => 'La tua richiesta è stata ricevuta',
);
