<?php

return array (
  'optdesc' => 'Vous pouvez utiliser ces packages pour une tombola Instagram avec plus de 2500 commentaires.',
  'Destek' => 'Soutien Technique',
  'Destekalt' => 'Vous pouvez parler à notre équipe technique à tout moment avec le soutien direct.',
  'Memnuniyet' => '100% Satisfaction des clients',
  'Memnuniyetalt' => 'Si vous ne le faites pas comme notre service que vous avez acheté votre argent sera remboursé sans',
  'yorumnekadar' => 'Combien de commentaires y a-t-il sur votre publication Instagram?',
  'cekilisfiyat' => 'Liste de prix',
  'onekyan' => 'Moins de commentaires',
  'sonekyan' => '',
  '2mfazlayorum' => 'Vous avez plus de 2.000.000 commentaires sur votre message Instagram?',
  'bizeyaz' => 'Obtenez Prix',
  'dahauygun' => '',
  'sadece' => 'Seulement',
  'satinal' => 'Achète-le',
  'nesunuyor' => 'Que pouvons-nous faire?',
  'araclar' => 'CekilisGram Outils',
  'bilgi1' => 'Vous pouvez faire illimitée avec le même tirages poste.',
  'bilgi2' => 'Vous pouvez déterminer le nombre de gagnants seront.',
  'bilgi3' => 'Vous pouvez déterminer les gagnants de substitution.',
  'bilgi4' => "Vous pouvez dessiner avec plus d'un poste Instagram.",
  'bilgi5' => 'Filtrage Tag',
  'bilgi6' => 'Filtrage de mots',
  'bilgi7' => 'Vous pouvez vérifier les disciples',
  'sayfa' => 'Paquets',
  'list2' => '3 encore pour le même poste',
  'list3' => 'Post combiner',
  'list4' => 'Contrôle des suiveurs',
  'list5' => 'Filtrage de mots',
  'list6' => 'Déterminer le nombre d\'étiquettes',
  'list7' => 'Pas de limite de temps',
  'list11' => 'Faire une tombola de 2500 commentaires',
  'list12' => 'Faire une tombola de 5000 commentaires',
  'list13' => 'Faire une tombola de 20000 commentaires',
  'list14' => 'Faire une tombola de 50000 commentaires',
  'list15' => 'Faire une tombola de 150000 commentaires',
  'list16' => 'Faire une tombola de 500000 commentaires',
  'list17' => 'Faire une tombola de 2000000 commentaires',
  '1p' => '(Pour 1 posté)',
  '3p' => '(Pour 3 posté)',
  '5p' => '(Pour 5 posté)',
);
