<?php

return array (
  'panel' => 'Panneau',
  'destek' => 'Service Clients',
  'ayarlar' => 'Paramètres',
  'cikisyap' => 'Déconnexion',
  'kontrolpaneli' => 'Tableau de contrôle',
  'merhaba' => 'Salut',
  'hosgeldin' => 'Bienvenue à Cekilisgram',
  'yardim' => 'Pouvons-nous vous aider?',
  'yardim2' => 'Veuillez soumettre une demande d\'assistance.',
  'sta1' => 'Personnes ont aimé leur dernière tombola',
  'sta2' => 'Personnes ont commenté la dernière tombola',
  'paketiniz' => 'Votre colis',
  'kadar' => 'Jusqu\'à',
  'kadar2' => 'commentaires',
  'kaldi' => 'Loterie restante',
  'son' => 'Tirage au sort récent',
  'cekilis2' => 'Veuillez écrire <span style="color:#3a00ff ">l\'adresse URL Instagram</span> pour organiser la tombola.',
  'adres' => 'URL',
  'ad' => 'Nom de la loterie',
  'asil' => 'Combien de personnes gagnent?',
  'takipciyok' => 'Ne pas vérifier les abonnés',
  'yedek' => 'Gagnant de la réserve',
  'icerdigi' => 'Quels mots?',
  'etiket' => 'Combien de balises?',
  'baslat' => 'Commencez la tombola',
  'konu' => 'Matière',
  'aciliyet' => 'Urgence',
  'acil' => 'Urgent',
  'acildegil' => 'Pas urgent',
  'cokacil' => 'Très urgent',
  'talindi' => 'Votre demande a été reçue',
);
