<?php

return array (
  'optdesc' => 'La forma más fácil de hacer un sorteo de Instagram Estás buscando una herramienta de sorteo para realizar sorteos de Instagram? Puede hacer un sorteo de millones de comentarios de inmediato y compartir los resultados.',
  'opttitle' => 'Sorteo de Instagram - CekilisGram',
  'Anasayfamenu' => 'Pagina Principal',
  'Özelliklermenu' => 'Especificaciones',
  'Çekilişyapmenu' => 'Hacer un Sorteo',
  'Referanslarımızmenu' => 'Referencias',
  'Blogmenu' => 'Blogs',
  'shop' => 'Mağaza',
  'İletişimmenu' => 'Contacto',
  'Girişyapmenu' => 'Iniciar Sesión',
  
  
  
  
  'header1' => 'La forma más fácil de hacer un <h1 class="font-weight-bold bg-light  px-2 ml-n2" style="width: fit-content;color:#3a00ff;border-radius: 10px"> sorteo de Instagram</h1>',
  'header2' => 'Estás buscando una herramienta de sorteo para realizar sorteos de Instagram? Puede hacer un sorteo de millones de comentarios de inmediato y compartir los resultados.',
  'headerbuton' => 'Hacer un Sorteo',
  'kullanım' => '¿Cómo usar CekilisGram?',
  'headerlist1' => 'Probada y Confiable!',
  'headerlist2' => 'Útil!',
  'headerlist3' => 'Fácil de usar!',
  'rakamlarbaslik1' => 'En la cumbre!',
  'rakamlarbaslik2' => 'Estadísticas',
  'rakamlarcekilis' => 'Las loterías',
  'rakamlarcekilis2' => 'fueron realizadas por Cekilisgram.',
  'rakamlarkullanici' => 'Personas',
  'rakamlarkullanici2' => 'usaron Cekilisgram para hacer un sorteo en Instagram',
  'rakamlaryorum' => 'Comentario',
  'rakamlaryorum2' => 'Sitio de rifa de Instagram donde los clientes continuos hacen comentarios positivos.',
  'enguvbaslik' => 'Sitio web más confiable para organizar la rifa de Instagram',
  'enguvicerik' => 'Usamos las redes sociales como medios de comunicación en los últimos años.<br><br>Si alguien dice las redes sociales, ¿qué se te ocurre primero? Por supuesto, Instagram. Instagram es una plataforma de redes sociales que alberga a millones de usuarios. Hay millones de usuarios, marcas, servicios de entretenimiento y boutiques en Instagram. Estas páginas compiten constantemente en Instagram.<br><br>Para obtener una audiencia en Instagram, es necesario anunciar a la audiencia objetivo. Es posible pero una forma costosa de hacer esto con anuncios patrocinados por Instagram. La forma más fácil y barata de anunciarse en Instagram es organizar un sorteo de Instagram. Como resultado del sorteo de Instagram que organizas, tu número de seguidores aumenta y puedes vender más productos.',
  'sorgubaslik1' => 'Resultados de la rifa de Instagram',
  'sorgubaslik2' => 'El código no funciona? Asegúrese de obtener el código correcto de la persona que organizó el sorteo de Instagram.',
  'igcbaslik1' => 'Cuál es el sorteo en instagram?',
  'igcbaslik2' => 'Cómo hacer un hacer sorteo en instagram?',
  'igcacik1' => 'Para aumentar sus seguidores, el conocimiento de su marca, sus pedidos y la sostenibilidad en Instagram, las rifas de Instagram son uno de los trabajos publicitarios y promocionales más importantes. El sorteo de Instagram es una herramienta publicitaria en la que los perfiles, como las marcas y las cuentas de humor, que son apreciados por la gente y se siguen con mucho cariño, inician el sorteo prometiendo productos que atraerán a sus seguidores. Por ejemplo; Hoy en día, la elección de productos como un teléfono móvil, tableta, computadora y cosméticos recientemente lanzados aumentará la participación en el sorteo más de lo esperado y alentará a otras personas a participar en el sorteo. La primera razón para hacer un sorteo es ganar seguidores. Con las condiciones que ejecuta para la campaña, puede llegar a millones de personas en días y ganar cientos de miles de seguidores gracias a elementos como compartir su campaña en la historia y etiquetar a su amigo. Al mismo tiempo, hacer un sorteo es el método publicitario más lógico para ganar el público objetivo.',
  'igcacik2' => 'En nuestra página web; Puedes elegir al ganador con el filtro que has elegido entre millones de comentarios en segundos, y compartirlo como una url con tus seguidores. Si bien cekilisgram.com les da a nuestros nuevos usuarios el derecho de sacar 1 uso para el sorteo, decenas de usuarios lo prefieren con nuestros paquetes asequibles.',
  'referanslarimiz' => 'Referencias',
  'listbaslik1' => 'El mejor sitio de rifas de Instagram del mundo',
  'listbaslik2' => 'El sitio web más rápido de la rifa de Instagram',
  'list1' => 'Si el sorteo que organiza tiene menos de 1000 comentarios, no necesita pagar.',
  'list2' => 'Con la pantalla de administración avanzada, puede organizar una lotería de Instagram con diferentes reglas.',
  'list3' => 'Su información personal nunca es registrada por Cekilisgram. Se proporciona un alto nivel de seguridad para el cliente.',
  'list4' => 'Ofrece la imagen más estética entre los sitios de rifa de Instagram con sus extraordinarias animaciones.',
  'list5' => 'Puede guardar su rifa de Instagram y compartirla con sus seguidores.',
  'ozelliklerbaslik' => 'Por qué deberías usar Cekilisgram?',
  'ozelb1' => 'Algoritmo de lotería',
  'ozel1' => 'El algoritmo desarrollado por un equipo de software profesional.',
  'ozelb2' => 'Sorteo rápido de Instagram',
  'ozel2' => 'Puede configurar el tiempo del hacer un sorteo.',
  'ozelb3' => 'El mejor diseño',
  'ozel3' => 'Interfaces desarrolladas por los mejores diseñadores del mundo.',
  'ozelb4' => 'Los paquetes de rifa más baratos',
  'ozel4' => 'Los paquetes de rifa de Instagram con los salarios más bajos del mercado.',
  'ozelb5' => 'Condiciones justas de lotería.',
  'ozel5' => 'Sorteo 100% justo, gracias al algoritmo de lotería único.',
  'ozelb6' => 'Servicio al cliente 24/7',
  'ozel6' => 'Servicio al cliente rápido con Whatsapp.',
  'alt1' => 'Estamos listos para el sorteo de Instagram. Estás listo?',
  'alt2' => 'Prueba Cekilisgram gratis.',
  'altb1' => 'Regístrate',
  'ara' => 'Buscar',
  'cekilissorgu' => 'Resultados de la rifa de Instagram',
  
  
  
  
  'fiyatlandirma' => 'Precios',
  'hakkimizda' => 'Sobre nosotros',
  'kurumsaliletisim' => 'Comunicaciones Corporativas',
  'gizlilikpolitikasi' => 'Política de privacidad',
  'cerezpolitikasi' => 'Cookies',
  'iptalveiade' => 'Politica de devolucion',
  'title' => 'Sitio de rifas de Instagram',
  'ara' => 'Buscar',
  'cekilissorgu' => 'Resultados de la rifa de Instagram',
  'footer1' => 'Todos los derechos reservados',
  'footer2' => 'Última actualización: 06.01.2021',
  'footer3' => 'Historial de actualizaciones',
);
