<?php

return array (
  'optdesc' => 'Puede usar estos paquetes para un sorteo de Instagram con más de 2500 comentarios.',
  'Destek' => 'Soporte técnico',
  'Destekalt' => 'Usted puede hablar con nuestro equipo técnico en cualquier momento con el apoyo directo.',
  'Memnuniyet' => '100% Satisfacción del Cliente',
  'Memnuniyetalt' => 'Si no lo hace como nuestro servicio adquirido su dinero será devuelto incondicionalmente.',
  'yorumnekadar' => '¿Cuántos comentarios hay en tu publicación de Instagram?',
  'cekilisfiyat' => 'Lista de Precios',
  'onekyan' => 'Menos de',
  'sonekyan' => 'comentarios',
  '2mfazlayorum' => 'Tienes más de 2,000,000 de comentarios en tu publicación de Instagram?',
  'bizeyaz' => 'Obtener precio',
  'dahauygun' => '',
  'sadece' => 'Solamente',
  'satinal' => 'Cómpralo',
  'nesunuyor' => 'Qué podemos hacer?',
  'araclar' => 'CekilisGram Herramientas',
  'bilgi1' => 'Usted puede hacer ilimitado dibuja con el mismo puesto.',
  'bilgi2' => 'Puede determinar cuántos serán los ganadores.',
  'bilgi3' => 'Puede determinar los ganadores suplentes.',
  'bilgi4' => 'Se puede dibujar con más de un puesto de Instagram.',
  'bilgi5' => 'Filtrado de etiqueta',
  'bilgi6' => 'Filtrado de palabra',
  'bilgi7' => 'Puedes consultar los seguidores',
  'sayfa' => 'Paquetes',
  'list2' => '3 repeticiones para la misma publicación',
  'list3' => 'Post-Combinar',
  'list4' => 'Control de seguidores',
  'list5' => 'Filtrado de palabras',
  'list6' => 'Determine cuántas etiquetas se sortearán',
  'list7' => 'Sin límite de tiempo',
  'list11' => 'Rifa de 2500 comentarios',
  'list12' => 'Rifa de 5000 comentarios',
  'list13' => 'Rifa de 20000 comentarios',
  'list14' => 'Rifa de 50000 comentarios',
  'list15' => 'Rifa de 150000 comentarios',
  'list16' => 'Rifa de 500000 comentarios',
  'list17' => 'Rifa de 2000000 comentarios',
  '1p' => '(Para 1 publicación)',
  '3p' => '(Para 3 publicación)',
  '5p' => '(Para 5 publicación)',
);
