<?php

return array (
  'panel' => 'Panel',
  'destek' => 'Servicio al Cliente',
  'ayarlar' => 'Configuraciones',
  'cikisyap' => 'Cerrar sesión',
  'kontrolpaneli' => 'Tabla de control',
  'merhaba' => 'Hola',
  'hosgeldin' => 'Bienvenido a Cekilisgram',
  'yardim' => 'Podemos ayudarte?',
  'yardim2' => 'Por favor envíe una solicitud de soporte.',
  'sta1' => 'Personas les gustó su último sorteo',
  'sta2' => 'Personas comentaron el último sorteo',
  'paketiniz' => 'Paquete de rifa',
  'kadar' => 'Hasta',
  'kadar2' => 'comentarios',
  'kaldi' => 'Quedan lotería(s)',
  'son' => 'Sorteos Recientes',
  'cekilis2' => 'Scrivi l\'indirizzo <span style="color:#3a00ff ">URL di Instagram </span> per organizzare la lotteria.',
  'adres' => 'Enlace',
  'ad' => 'Nombre de lotería',
  'asil' => 'Cuántos personas ganarán?',
  'takipciyok' => 'No verifique seguidores',
  'yedek' => 'Ganador de reserva',
  'icerdigi' => 'Que palabras?',
  'etiket' => 'Cuantas etiquetas?',
  'baslat' => 'Comience el sorteo',
  'konu' => 'Tema',
  'aciliyet' => 'Urgencia',
  'acil' => 'Urgente',
  'acildegil' => 'No urgente',
  'cokacil' => 'Muy urgente',
  'talindi' => 'Su petición ha sido recibida',
);
